import Footer from '@/components/layouts/Footer';
import Header from '@/components/layouts/Header/Header';
import type { Metadata } from 'next';
import { Montserrat, Open_Sans } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const montserrat = Montserrat({
  variable: '--font-heading',
  subsets: ['latin'],
});

const openSans = Open_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'DevConsult - ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${montserrat.variable} ${openSans.variable} antialiased bg-background text-foreground font-sans text-base grid grid-rows-[auto_1fr_auto] min-h-dvh`}>
        <Header />
        <main className='min-w-0'>{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
